language: "node_js"
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "3" # io.js
  - "2" # io.js
  - "1" # io.js
  - "0.12"
  - "0.10"
  - "0.8"
  - "0.6"


before_install:
  - "npm install make-node@0.3.x -g"
  - "preinstall-compat"

script:
  - "make test-cov"

after_success:
  - "make report-cov"

sudo: false
